name: Move GitHub Project Tasks on Push

on:
  push:
    branches:
      - main
      - TestAutomaticTaskMovement
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  manage-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Move Linked Issues to Done
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          user: EkitaiKani
          project_id: 2
          resource_node_id: ${{ github.event.pull_request.node_id || 'default-node-id' }}
          move_related_issues: true
          status_value: 'Done'
