name: Move GitHub Project Tasks on Push

on:
  push:
    branches:
      - main
      - TestAutomaticTaskMovement

jobs:
  manage-project:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Get PR Description and Issue Number
        id: pr
        run: |
          pr_number=${{ github.event.pull_request.number }}
          
          pr_description=$(curl -s -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number" | jq -r .body)
          
          issue_number=$(echo "$pr_description" | grep -o '#[0-9]\+' | sed 's/#//')
          
          echo "Issue Number: $issue_number"

      - name: Move Linked Issues to Done
        uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_token: ${{ secrets.GH_TOKEN }}
          user: EkitaiKani
          project_id: 2
          issue_number: ${{ steps.pr.outputs.issue_number }} 
          move_related_issues: true
          status_value: 'Done'
