name: deploy

on:
  push:
    branches:
      - Deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RENDER_SERVICE_ID: srv-cub0n952ng1s73al9d10
      RENDER_API_KEY: rnd_LCopwoiRrFjrciCuPrJaJodXhrbu
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Render Deployment
        run: |
          RESPONSE=$(curl -s -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
               -H "Authorization: Bearer $RENDER_API_KEY" \
               -H "Content-Type: application/json")
