name: Move Task to Done on PR Merge

on:
  pull_request:
    types:
      - closed

jobs:
  move-task:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get Issue linked to PR and Move task to Done
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Step 1: Check if PR was merged
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            PR_NUMBER="${{ github.event.pull_request.number }}"
            echo "Debug: PR Number = $PR_NUMBER"

            # Step 2: Fetch PR details
            echo "Debug: Fetching PR details from GitHub API"
            PR_DETAILS=$(curl -s -H "Authorization: token $GH_TOKEN" \
                "https://api.github.com/repos/EkitaiKani/DOPAssignment/pulls/$PR_NUMBER")
            
            echo "Debug: Raw PR Details = $PR_DETAILS"

            # Step 3: Extract PR body
            PR_BODY=$(echo "$PR_DETAILS" | jq -r '.body')
            echo "Debug: PR Body = $PR_BODY"

            # Step 4: Extract Issue Number from PR Body
            ISSUE_NUMBER=$(echo "$PR_BODY" | grep -o '#[0-9]\+' | tr -d '#')
            echo "Debug: Extracted Issue Number = $ISSUE_NUMBER"

            if [ -n "$ISSUE_NUMBER" ]; then
              echo "Debug: Found linked issue #$ISSUE_NUMBER"
              # (Move the task in GitHub Project here)
            else
              echo "Debug: No issue linked to PR #$PR_NUMBER"
            fi
          else
            echo "Debug: PR was closed but not merged, skipping task movement."
          fi
