name: Move tasks to done on push

on:
  push:
    branches:
      - main
      - TestAutomaticTaskMovement

jobs:
  move-task:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Get Issue linked to PR and Move task to Done
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          PR_NUMBER=${GITHUB_REF#refs/pull/}
          PR_NUMBER=${PR_NUMBER%/merge}

          ISSUE_NUMBER=$(curl -s -H "Authorization: token $GH_TOKEN" \
              "https://api.github.com/repos/EkitaiKani/DOPAssignment/pulls/$PR_NUMBER" | \
              jq -r '.body' | grep -o '#[0-9]\+' | tr -d '#')

          if [ -n "$ISSUE_NUMBER" ]; then
            echo "Found linked issue number: $ISSUE_NUMBER"

            CARD_ID=$(curl -s -H "Authorization: token $GH_TOKEN" \
                "https://api.github.com/repos/EkitaiKani/DOPAssignment/issues/$ISSUE_NUMBER" | \
                jq -r '.project_cards[0].id')

            if [ -n "$CARD_ID" ]; then
              echo "Moving task #$ISSUE_NUMBER to Done column"
              curl -X POST -H "Authorization: token $GH_TOKEN" \
                -d '{"column_id": "DoneColumnID"}' \
                "https://api.github.com/projects/columns/cards/$CARD_ID/moves"
            else
              echo "No project card found for issue #$ISSUE_NUMBER"
            fi
          else
            echo "No issue linked to PR #$PR_NUMBER"
          fi
