name: Issue Notification
on:
  issues:
    types: [opened]
  workflow_dispatch:  # Enables manual trigger

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: Sniddl/discord-commits@v1.6
        with:
          webhook: ${{ secrets.DISCORD_ISSUES_URL }}
          template: "avatar-with-link"
          message: |
            🆕 New Issue Opened!
            **Title:** ${{ github.event.issue.title }}
            **Description:** ${{ github.event.issue.body }}
            **Created by:** ${{ github.event.issue.user.login }}
            **Link:** ${{ github.event.issue.html_url }}

      - name: Send Telegram Notification
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_ISSUES }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
          -H "Content-Type: application/json" \
          -d "{
            \"chat_id\": \"${TELEGRAM_CHAT_ID}\",
            \"parse_mode\": \"Markdown\",
            \"text\": \"🆕 *New Issue Opened!*\n\n*Title:* ${ISSUE_TITLE}\n*Created by:* ${ISSUE_AUTHOR}\n[View Issue](${ISSUE_URL})\"
          }"
