name: Issue Notification
on:
  issues:
    types: [opened]

  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send issue to Discord
        uses: Ilshidur/action-discord@master
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_ISSUES_URL }}
        with:
          args: '🆕 New Issue Created: "${{ github.event.issue.title }}" by ${{ github.event.issue.user.login }} - ${{ github.event.issue.html_url }}'
        
      - name: Send issue to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOPIC_ID: ${{ secrets.TELEGRAM_ISSUES }}  # Rename to TOPIC_ID
          GITHUB_ISSUE_TITLE: ${{ github.event.issue.title }}
          GITHUB_ISSUE_BODY: ${{ github.event.issue.body }}
          GITHUB_ISSUE_URL: ${{ github.event.issue.html_url }}
          GITHUB_ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
        run: |
          curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
          -d chat_id="${TELEGRAM_CHAT_ID}" \
          -d message_thread_id="${TELEGRAM_TOPIC_ID}" \
          -d parse_mode="MarkdownV2" \
          -d text="*New Issue Created* 🛠️  
          *Title:* `${GITHUB_ISSUE_TITLE}`  
          *Author:* ${GITHUB_ISSUE_AUTHOR}  
          *Description:*  
          ${GITHUB_ISSUE_BODY}  
          [View Issue](${GITHUB_ISSUE_URL})"
