name: Login test
run-name: ${{ github.actor }} is testing the Login

on:
  push:
    branches:
      - github-actions

jobs:
  setup:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: database-setup
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: List repo
        run: ls

      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
      
      - name: Verify PostgreSQL installation
        run: |
          psql --version
          pg_isready

      - name: Test database connection
        run: |
          PGPASSWORD=mypassword psql -U myuser -d database-setup -c "\l"

      # Initialize database using database-setup.sql
      - name: Initialize database
        run: |
          PGPASSWORD=mypassword psql -U myuser -d database-setup -f database-setup.sql

      - name: Verify database setup
        run: |
          PGPASSWORD=mypassword psql -U myuser -d database-setup -c "SELECT COUNT(*) FROM students;"
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Create .env file 
      - name: Create .env file
        run: |
          echo "# Database Configuration" > .env
          echo "DB_NAME=database-setup" >> .env
          echo "DB_USER=myuser" >> .env
          echo "DB_PASSWORD=mypassword" >> .env
          echo "DB_HOST=localhost" >> .env

      - name: Setup Chrome and Chrome Webdriver
        uses: browser-actions/setup-chrome@v1
      
      - name: Check Chrome version
        run: chrome --version

