name: Login test
run-name: ${{ github.actor }} is testing the Login

on:
  push:
    branches:
      - github-actions

jobs:
  behave-testing:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: List repo
        run: ls
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Setup Chrome and Chrome Webdriver
        uses: browser-actions/setup-chrome@v1
      
      - name: Check Chrome version
        run: chrome --version
      
      - name: Run Behave tests
        run: behave tests/features/