name: Login test
run-name: ${{ github.actor }} is testing the Login

on:
  push:
    branches:
      - github-actions

jobs:
  setup:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: List repo
        run: ls
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Create .env file 
      - name: Create .env file
        run: |
          echo "# Database Configuration" > .env
          echo "DB_NAME=database-setup" >> .env
          echo "DB_USER=myuser" >> .env
          echo "DB_PASSWORD=mypassword" >> .env
          echo "DB_HOST=localhost" >> .env
        shell: cmd

      # install postgresql
      - name: Setup PostgreSQL
        uses: tj-actions/install-postgresql@v3
        with:
          postgresql-version: 17

      - name: Verify PostgreSQL installation
          run: |
            psql --version
            pg_isready
          shell: cmd

      - name: Create database and user
        run: |
          set PGPASSWORD=postgres
          psql -U postgres -c "CREATE DATABASE \"database-setup\";"
          psql -U postgres -c "CREATE USER myuser WITH PASSWORD 'mypassword';"
          psql -U postgres -c "GRANT ALL PRIVILEGES ON DATABASE \"database-setup\" TO myuser;"
        shell: cmd
      
      - name: Setup Chrome and Chrome Webdriver
        uses: browser-actions/setup-chrome@v1
      
      - name: Check Chrome version
        run: chrome --version

      - name: Test database connection
        run: |
          set PGPASSWORD=mypassword
          psql -U myuser -d database-setup -c "\l"
        shell: cmd
      
      # init database using database-setup.sql
      - name: Initialize database
        run: |
          set PGPASSWORD=mypassword
          psql -U myuser -d database-setup -f database-setup.sql
        shell: cmd

      - name: Verify database setup
        run: |
          set PGPASSWORD=mypassword
          
          REM Check if tables exist
          psql -U myuser -d database-setup -c "SELECT COUNT(*) FROM students;"        
        shell: cmd